name: learning_entity_extraction
description: The easy way to use ML Kit for entity extraction in Flutter.
version: 0.0.3
# author: Salman S
homepage: https://github.com/salkuadrat/learning/tree/master/packages/learning_entity_extraction
repository: https://github.com/salkuadrat/learning/tree/master/packages/learning_entity_extraction

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.salkuadrat.learning.learning_entity_extraction
        pluginClass: LearningEntityExtractionPlugin
      ios:
        pluginClass: LearningEntityExtractionPlugin
